name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: marttp/github-stats-creator@v1
        with:
          theme: dark
          output_path: gh-stats.svg
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Update GitHub stats SVG file
